apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-credentials
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: example.example-org.io
type: Opaque
stringData:
  password: ""
