apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.example.example-org.io
spec:
  service:
    name: example-service-apiserver
      port: 443
  group: example.example-org.io
  version: v1alpha1
  insecureSkipTLSVerify: false
  groupPriorityMinimum: 1000
  versionPriority: 15
